version: '3.7'

services:
  traduora:
    image: everco/ever-traduora:latest
    container_name: traduora
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
    ports:
      - '80:8080'
    environment:
      TR_DB_TYPE: mysql
      TR_DB_USER: ${RDS_DB_USER:-tr}
      TR_DB_PASSWORD: ${RDS_DB_PASSWORD:-change_me}
      TR_DB_DATABASE: ${RDS_DB_NAME:-tr_dev}
      TR_DB_HOST: ${TR_DB_HOST}
      TR_DB_PORT: 3306
      NODE_ENV: ${NODE_ENV:-production}
    entrypoint: './docker-entrypoint.compose.sh'
    restart: on-failure
    networks:
      - overlay

networks:
  overlay:
    driver: bridge
