version: '3.7'

services:
  traduora:
    image: everco/ever-traduora:latest
    container_name: traduora
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
    ports:
      - '80:8080'
    environment:
      TR_DB_TYPE: mysql
      TR_DB_USER: tr
      TR_DB_PASSWORD: ${TR_DB_PASSWORD:-change_me}
      TR_DB_DATABASE: ${TR_DB_DATABASE:-tr_dev}
      TR_DB_HOST: mysqldb
      TR_DB_PORT: 3306
      NODE_ENV: ${NODE_ENV:-production}
    entrypoint: './docker-entrypoint.compose.sh'
    restart: on-failure
    depends_on:
      - mysqldb
    networks:
      - overlay

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-tr_dev}
      MYSQL_USER: ${MYSQL_USER:-tr}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-change_me}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    networks:
      - overlay

networks:
  overlay:
    driver: bridge
